<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>3.4.7</version>
        <relativePath/>
    </parent>

    <groupId>com.coinly</groupId>
    <artifactId>backend-java</artifactId>
    <version>0.0.1-SNAPSHOT</version>
    <packaging>pom</packaging>

    <name>backend-java</name>
    <description>Coinly Backend Service</description>

    <modules>
        <module>coinly-common</module>
        <module>coinly-integration</module>
        <module>coinly-business</module>
        <module>coinly-system</module>
    </modules>

    <properties>
        <java.version>17</java.version>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <mybatis-plus.version>3.5.7</mybatis-plus.version>
    </properties>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>com.coinly</groupId>
                <artifactId>coinly-common</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>com.coinly</groupId>
                <artifactId>coinly-integration</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>com.coinly</groupId>
                <artifactId>coinly-business</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>com.coinly</groupId>
                <artifactId>coinly-system</artifactId>
                <version>${project.version}</version>
            </dependency>
        </dependencies>
    </dependencyManagement>

</project>
